# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    replaces = [(b'videos', '0001_initial'), (b'videos', '0002_video_video'), (b'videos', '0003_auto_20160716_2056')]

    initial = True

    dependencies = [
        ('cms', '0003_auto_20140926_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('main_image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'')),
                ('video', embed_video.fields.EmbedVideoField(default=b'https://vimeo.com/142393949')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='VideosPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='videos_videospluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default=b'Videos', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
