# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videospluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='videos_videospluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
