# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squashed_0022_auto_20160716_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocationhours',
            name='weekday',
            field=models.IntegerField(choices=[(1, b'Monday'), (2, b'Tuesday'), (3, b'Wednesday'), (4, b'Thursday'), (5, b'Friday'), (6, b'Saturday'), (7, b'Sunday')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventlocationhours',
            unique_together=set([('event', 'weekday')]),
        ),
    ]
