# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 07:21
from __future__ import unicode_literals

import cms.models.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    replaces = [(b'articles', '0001_initial'), (b'articles', '0002_article_original_publication_date_label'), (b'articles', '0003_article_tags'), (b'articles', '0004_auto_20150908_1105'), (b'articles', '0005_auto_20160716_2056')]

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cms', '0003_auto_20140926_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=512, null=True)),
                ('original_publication_date', models.DateField(default=datetime.date.today)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('lead_content', models.TextField(blank=True, null=True)),
                ('screenshot', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'')),
                ('screenshot_2', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'')),
                ('content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=b'press_item_content', to=b'cms.Placeholder')),
                ('original_publication_date_label', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='LatestArticlesPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='articles_latestarticlespluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('number_to_show', models.PositiveSmallIntegerField(default=4)),
                ('title', models.CharField(default=b'Latest Articles', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
