# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxFileMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dropbox_id', models.CharField(max_length=255)),
                ('client_modified', models.DateTimeField()),
                ('server_modified', models.DateTimeField()),
                ('rev', models.CharField(max_length=256)),
                ('size', models.PositiveIntegerField()),
                ('path_lower', models.CharField(max_length=2048)),
                ('path_display', models.CharField(max_length=2048)),
                ('parent_shared_folder_id', models.CharField(max_length=256)),
                ('export_type', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=128)),
            ],
        ),
    ]
