# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_import', '0002_remove_dropboxfilemetadata_parent_shared_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.PositiveIntegerField()),
                ('quantity', models.SmallIntegerField()),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dropboxfilemetadata',
            options={'get_latest_by': 'server_modified'},
        ),
    ]
