branch-defaults:
  devel:
    environment: press-section-development
  master:
    environment: null
  webhook:
    environment: press-section-development
global:
  application_name: press_section
  default_ec2_keyname: theia-api
  default_platform: Python 2.7
  default_region: us-east-1
  profile: default
  sc: git
