# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 07:28
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    replaces = [(b'celebrities', '0001_initial'), (b'celebrities', '0002_celebritiespluginmodel'), (b'celebrities', '0003_celebritiespluginmodel_title'), (b'celebrities', '0004_auto_20150908_1105'), (b'celebrities', '0005_auto_20150908_1125'), (b'celebrities', '0006_auto_20160716_2056')]

    initial = True

    dependencies = [
        ('cms', '0003_auto_20140926_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('byline', models.CharField(blank=True, max_length=128, null=True)),
                ('main_image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=b'celebrity_content', to=b'cms.Placeholder')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
                'verbose_name': 'Celebrity',
                'verbose_name_plural': 'Celebrities',
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebrities.Celebrity')),
                ('content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=b'celebrity_content', to=b'cms.Placeholder')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Dress',
                'verbose_name_plural': 'Dresses',
            },
        ),
        migrations.CreateModel(
            name='CelebritiesPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='celebrities_celebritiespluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('number_to_show', models.PositiveSmallIntegerField(default=4)),
                ('title', models.CharField(default=b'Celebrities', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='celebrity',
            options={'ordering': ['order'], 'verbose_name': 'Celebrity', 'verbose_name_plural': 'Celebrities'},
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterModelOptions(
            name='dress',
            options={'verbose_name': 'Dress', 'verbose_name_plural': 'Dresses'},
        ),
    ]
