# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0005_auto_20150908_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebritiespluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='celebrities_celebritiespluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
