# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'press_contacts', '0001_initial'), (b'press_contacts', '0002_auto_20150226_1445'), (b'press_contacts', '0003_auto_20150914_1226'), (b'press_contacts', '0004_presscontact_url_label'), (b'press_contacts', '0005_auto_20160716_2056')]

    initial = True

    dependencies = [
        ('cms', '0003_auto_20140926_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive_text', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PressContactPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='press_contacts_presscontactpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('press_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='press_contacts.PressContact')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='presscontact',
            name='address',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='presscontact',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presscontact',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presscontact',
            name='descriptive_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presscontact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presscontact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presscontact',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='presscontact',
            name='url_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
